# Make sure to check the documentation at http://goreleaser.com
builds:
  - binary: dist/carnot
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64

archive:
  format: tar.gz
  format_overrides:
  - goos: windows
    format: zip

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^chore:'
    - '^refactor:'

brew:
  github:
    owner: wejustdostuff
    name: homebrew-carnot
  homepage: "https://github.com/wejustdostuff/carnot"
  description: "Small utility to copy/move files from a source directory to a target directory and organize them by date"
